const mockGraphData = {
    nodes: [
        { topic: 'Binary Search', support: 12 },
        { topic: 'Dynamic Programming', support: 18 },
        { topic: 'Graph Algorithms', support: 15 },
        { topic: 'Hash Tables', support: 10 },
        { topic: 'Linked Lists', support: 8 },
        { topic: 'Trees', support: 14 },
        { topic: 'Sorting', support: 11 },
        { topic: 'Recursion', support: 9 },
        { topic: 'BFS', support: 7 },
        { topic: 'DFS', support: 7 },
        { topic: 'Greedy Algorithms', support: 6 },
        { topic: 'Sliding Window', support: 5 },
        { topic: 'Two Pointers', support: 8 },
        { topic: 'Stack', support: 6 },
        { topic: 'Queue', support: 4 },
        { topic: 'Heap', support: 5 },
        { topic: 'Trie', support: 3 },
        { topic: 'Backtracking', support: 7 },
        { topic: 'Bit Manipulation', support: 4 },
        { topic: 'System Design', support: 10 },
    ],
    edges: [
        { source: 'Binary Search', target: 'Sorting', edgeType: 'related_to', weight: 5, confidence: 0.82 },
        { source: 'Binary Search', target: 'Two Pointers', edgeType: 'related_to', weight: 3, confidence: 0.55 },
        { source: 'Dynamic Programming', target: 'Recursion', edgeType: 'prerequisite_of', weight: 8, confidence: 0.95 },
        { source: 'Dynamic Programming', target: 'Greedy Algorithms', edgeType: 'related_to', weight: 4, confidence: 0.65 },
        { source: 'Dynamic Programming', target: 'Backtracking', edgeType: 'related_to', weight: 3, confidence: 0.50 },
        { source: 'Graph Algorithms', target: 'BFS', edgeType: 'prerequisite_of', weight: 7, confidence: 0.90 },
        { source: 'Graph Algorithms', target: 'DFS', edgeType: 'prerequisite_of', weight: 7, confidence: 0.90 },
        { source: 'Graph Algorithms', target: 'Trees', edgeType: 'related_to', weight: 6, confidence: 0.80 },
        { source: 'Hash Tables', target: 'Two Pointers', edgeType: 'related_to', weight: 2, confidence: 0.40 },
        { source: 'Hash Tables', target: 'Sliding Window', edgeType: 'related_to', weight: 2, confidence: 0.38 },
        { source: 'Linked Lists', target: 'Two Pointers', edgeType: 'used_in', weight: 4, confidence: 0.70 },
        { source: 'Linked Lists', target: 'Stack', edgeType: 'related_to', weight: 3, confidence: 0.55 },
        { source: 'Trees', target: 'BFS', edgeType: 'used_in', weight: 5, confidence: 0.78 },
        { source: 'Trees', target: 'DFS', edgeType: 'used_in', weight: 5, confidence: 0.78 },
        { source: 'Trees', target: 'Heap', edgeType: 'variant_of', weight: 3, confidence: 0.52 },
        { source: 'Trees', target: 'Trie', edgeType: 'variant_of', weight: 2, confidence: 0.42 },
        { source: 'Sorting', target: 'Heap', edgeType: 'used_in', weight: 3, confidence: 0.58 },
        { source: 'Recursion', target: 'Backtracking', edgeType: 'prerequisite_of', weight: 6, confidence: 0.85 },
        { source: 'Recursion', target: 'DFS', edgeType: 'used_in', weight: 4, confidence: 0.68 },
        { source: 'Stack', target: 'DFS', edgeType: 'used_in', weight: 3, confidence: 0.55 },
        { source: 'Stack', target: 'Queue', edgeType: 'related_to', weight: 2, confidence: 0.35 },
        { source: 'Queue', target: 'BFS', edgeType: 'used_in', weight: 4, confidence: 0.72 },
        { source: 'Sliding Window', target: 'Two Pointers', edgeType: 'variant_of', weight: 4, confidence: 0.70 },
        { source: 'System Design', target: 'Hash Tables', edgeType: 'used_in', weight: 3, confidence: 0.60 },
        { source: 'System Design', target: 'Graph Algorithms', edgeType: 'related_to', weight: 2, confidence: 0.45 },
    ],
};

export default mockGraphData;